/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.SpaceStationToUI;
import deepspace.DamageToUI;
import deepspace.ShieldToUI;
import deepspace.WeaponToUI;
import java.awt.Component;
import java.util.ArrayList;

/**
 *
 * @author Lucía Salamanca López
 *         Celia Arias Martínez
 */
public class StationView extends javax.swing.JPanel {

    /**
     * Creates new form StationView
     */
    public StationView() {
        initComponents();
    }

    void setStation(SpaceStationToUI station){
        jlNameStation.setText(station.getName());
        jlAmmoPower.setText(Float.toString(station.getAmmoPower()));
        jlFuelUnits.setText(Float.toString(station.getFuelUnits()));
        jlShieldPower.setText(Float.toString(station.getShieldPower()));
        jlNMedals.setText(Float.toString(station.getnMedals()));
       
       
        if (station.getPendingDamage() != null){
            jlWeaponPD.setText(station.getPendingDamage().getWeaponInfo());
            jlShieldsPD.setText(Integer.toString(station.getPendingDamage().getNShields()));
        }
        else{
            jlWeaponPD.setText("");
            jlShieldsPD.setText("");
        }
        
        
        panelWeapons.removeAll();
        ArrayList<WeaponToUI> stations = station.getWeapons();
        Weapon weV;
        
        for (WeaponToUI we : stations) {
            weV = new Weapon();
            weV.setWeapon(we);
            panelWeapons.add(weV);
            
        }
        
        
        panelShields.removeAll();
        ArrayList<ShieldToUI> shields = station.getShieldBoosters();
        ShieldBooster shV;
        for (ShieldToUI sh: shields){
            shV = new ShieldBooster();
            shV.setShieldBooster(sh);
            panelShields.add(shV);
        }
        
        panelHangar.removeAll();
        Hangar hangarV = new Hangar();
        hangarV.setHangar(station.getHangar());
        panelHangar.add(hangarV);
        
        
        repaint();
        revalidate();
        
    }
    
   
    
    ArrayList<Integer> getSelectedWeapons () {
        ArrayList<Integer> selectedWeapons = new ArrayList<>();
        int i = 0;
        for (Component c : panelWeapons.getComponents()) {
            if (((Weapon) c).isSelected()) {
                selectedWeapons.add(i);
            }
            i++;
        }
        return selectedWeapons;
    }
    
    ArrayList<Integer> getSelectedShields () {
        ArrayList<Integer> selectedShields = new ArrayList<>();
        int i = 0;
        for (Component c : panelShields.getComponents()) {
            if (((ShieldBooster) c).isSelected()) {
                selectedShields.add(i);
            }
            i++;
        }
        return selectedShields;
    }
    
    ArrayList<Integer> getSelectedHangarWeapons(){
        return ((Hangar) panelHangar.getComponents()[0]).getSelectedWeapons();
    }
    
    ArrayList<Integer> getSelectedHangarShields(){
        return ((Hangar) panelHangar.getComponents()[0]).getSelectedShields();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelScrollWeapons = new javax.swing.JScrollPane();
        panelWeapons = new javax.swing.JPanel();
        panelScrollShields = new javax.swing.JScrollPane();
        panelShields = new javax.swing.JPanel();
        panelScrollHangar = new javax.swing.JScrollPane();
        panelHangar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlAmmoPower = new javax.swing.JLabel();
        jlShieldPower = new javax.swing.JLabel();
        jlFuelUnits = new javax.swing.JLabel();
        jlNMedals = new javax.swing.JLabel();
        jlNameStation = new javax.swing.JLabel();
        jpPendingDamage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlShieldsPD = new javax.swing.JLabel();
        jlWeaponPD = new javax.swing.JLabel();

        panelScrollWeapons.setName(""); // NOI18N
        panelScrollWeapons.setViewportView(panelWeapons);

        panelScrollShields.setViewportView(panelShields);

        panelScrollHangar.setViewportView(panelHangar);

        jLabel1.setText("Potencia de Ataque: ");

        jLabel2.setText("Potencia de Defensa:");

        jLabel3.setText("Nivel de Combustible");

        jLabel4.setText("Medallas:");

        jlAmmoPower.setText("jLabel5");

        jlShieldPower.setText("jLabel6");

        jlFuelUnits.setText("jLabel7");

        jlNMedals.setText("jLabel8");

        jlNameStation.setFont(new java.awt.Font("San Francisco Display Light", 1, 24)); // NOI18N
        jlNameStation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jpPendingDamage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Castigo Pendiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16))); // NOI18N

        jLabel5.setText("Escudos:");

        jLabel6.setText("Armas:");

        jlShieldsPD.setText("jLabel7");

        jlWeaponPD.setText("jLabel8");

        javax.swing.GroupLayout jpPendingDamageLayout = new javax.swing.GroupLayout(jpPendingDamage);
        jpPendingDamage.setLayout(jpPendingDamageLayout);
        jpPendingDamageLayout.setHorizontalGroup(
            jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPendingDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPendingDamageLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlShieldsPD))
                    .addGroup(jpPendingDamageLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jlWeaponPD)))
                .addGap(143, 143, 143))
        );
        jpPendingDamageLayout.setVerticalGroup(
            jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPendingDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlShieldsPD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlWeaponPD))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlNameStation, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(258, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlShieldPower))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNMedals)
                                    .addComponent(jlFuelUnits)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jlAmmoPower)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelScrollWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelScrollHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelScrollShields, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNameStation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlAmmoPower))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jlShieldPower))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jlFuelUnits, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jlNMedals)))
                    .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelScrollWeapons, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelScrollShields, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScrollHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jlAmmoPower;
    private javax.swing.JLabel jlFuelUnits;
    private javax.swing.JLabel jlNMedals;
    private javax.swing.JLabel jlNameStation;
    private javax.swing.JLabel jlShieldPower;
    private javax.swing.JLabel jlShieldsPD;
    private javax.swing.JLabel jlWeaponPD;
    private javax.swing.JPanel jpPendingDamage;
    private javax.swing.JPanel panelHangar;
    private javax.swing.JScrollPane panelScrollHangar;
    private javax.swing.JScrollPane panelScrollShields;
    private javax.swing.JScrollPane panelScrollWeapons;
    private javax.swing.JPanel panelShields;
    private javax.swing.JPanel panelWeapons;
    // End of variables declaration//GEN-END:variables
}
