/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import deepspace.SpaceStationToUI;
import deepspace.DamageToUI;

/**
 *
 * @author lucia
 */
public class StationView extends javax.swing.JPanel {

    /**
     * Creates new form StationView
     */
    public StationView() {
        initComponents();
    }

    void setStation(SpaceStationToUI station){
        jlNameStation.setText(station.getName());
        jlAmmoPower.setText(Float.toString(station.getAmmoPower()));
        jlFuelUnits.setText(Float.toString(station.getFuelUnits()));
        jlShieldPower.setText(Float.toString(station.getShieldPower()));
        jlNMedals.setText(Float.toString(station.getnMedals()));
    }
    
    void setPendingDamage(DamageToUI danio){
        jlWeaponPD.setText(danio.getWeaponInfo());
        jlShieldsPD.setText(Integer.toString(danio.getNShields()));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollWeapon = new javax.swing.JScrollPane();
        jScrollShieldBooster = new javax.swing.JScrollPane();
        jScrollHangar = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlAmmoPower = new javax.swing.JLabel();
        jlShieldPower = new javax.swing.JLabel();
        jlFuelUnits = new javax.swing.JLabel();
        jlNMedals = new javax.swing.JLabel();
        jlNameStation = new javax.swing.JLabel();
        jpPendingDamage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlShieldsPD = new javax.swing.JLabel();
        jlWeaponPD = new javax.swing.JLabel();

        jScrollWeapon.setName(""); // NOI18N

        jLabel1.setText("Potencia de Ataque: ");

        jLabel2.setText("Potencia de Defensa:");

        jLabel3.setText("Nivel de Combustible");

        jLabel4.setText("Medallas:");

        jlAmmoPower.setText("jLabel5");

        jlShieldPower.setText("jLabel6");

        jlFuelUnits.setText("jLabel7");

        jlNMedals.setText("jLabel8");

        jlNameStation.setFont(new java.awt.Font("San Francisco Display Light", 1, 24)); // NOI18N
        jlNameStation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlNameStation.setText("jLabel5");

        jpPendingDamage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Castigo Pendiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 16))); // NOI18N

        jLabel5.setText("Escudos:");

        jLabel6.setText("Armas:");

        jlShieldsPD.setText("jLabel7");

        jlWeaponPD.setText("jLabel8");

        javax.swing.GroupLayout jpPendingDamageLayout = new javax.swing.GroupLayout(jpPendingDamage);
        jpPendingDamage.setLayout(jpPendingDamageLayout);
        jpPendingDamageLayout.setHorizontalGroup(
            jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPendingDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPendingDamageLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlShieldsPD))
                    .addGroup(jpPendingDamageLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jlWeaponPD)))
                .addGap(143, 143, 143))
        );
        jpPendingDamageLayout.setVerticalGroup(
            jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPendingDamageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlShieldsPD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpPendingDamageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlWeaponPD))
                .addGap(76, 76, 76))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollShieldBooster, javax.swing.GroupLayout.PREFERRED_SIZE, 858, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNameStation, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlShieldPower))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNMedals)
                                    .addComponent(jlFuelUnits)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jlAmmoPower)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jlNameStation)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jlAmmoPower))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jlShieldPower))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jlFuelUnits, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jlNMedals)))
                    .addComponent(jpPendingDamage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollWeapon, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollShieldBooster, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollHangar;
    private javax.swing.JScrollPane jScrollShieldBooster;
    private javax.swing.JScrollPane jScrollWeapon;
    private javax.swing.JLabel jlAmmoPower;
    private javax.swing.JLabel jlFuelUnits;
    private javax.swing.JLabel jlNMedals;
    private javax.swing.JLabel jlNameStation;
    private javax.swing.JLabel jlShieldPower;
    private javax.swing.JLabel jlShieldsPD;
    private javax.swing.JLabel jlWeaponPD;
    private javax.swing.JPanel jpPendingDamage;
    // End of variables declaration//GEN-END:variables
}
